version: "3.9"
services :
  web: 
    image : sushanth956/devops:latest
    container: devops_app
    ports :
     -"8082:8082"
    depends_on:
     -redis
    environment:
     -REDIS_HOST=redis
     -REDIS_PORT=6379
  redis:
    image: redis:alpine
    container_name: devops_redis
    ports:
     -"6379:6379"