name: Build & Deploy to ACI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build & Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project0:latest

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to ACI
      - name: Deploy to ACI
        run: |
          echo "Deleting old container if exists..."
          az container delete \
            --resource-group project0 \
            --name project0-instance \
            --yes || true

          echo "Deploying new container..."
          az container create \
            --resource-group project0 \
            --name project0-instance \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/project0:latest \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --ports 8082 \
            --dns-name-label project0-demo123 \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Show deployed container FQDN
        run: |
          az container show \
            --resource-group project0 \
            --name project0-instance \
            --query ipAddress.fqdn -o tsv 